env = Environment()
LIBPATH = ['../libs/.']
cxxflags=['-std=c++17']
LIBS=['tcp','boost_regex','boost_unit_test_framework']
LINKFLAGS=  ['-lpthread','-pthread']
tcp_source =[
        '../tcp/network/io_service.cpp',
        '../tcp/network/tcp_client.cpp',
        '../tcp/network/tcp_server.cpp',
        '../tcp/network/common/tcp_socket.cpp',
        '../tcp/network/unix/unix_self_pipe.cpp',
        '../tcp/network/unix/unix_tcp_socket.cpp',
        '../tcp/network/windows/windows_self_pipe.cpp',
        '../tcp/network/windows/windows_tcp_socket.cpp',
        '../tcp/utils/error.cpp',
        '../tcp/utils/logger.cpp',
        '../tcp/utils/thread_pool.cpp'
]
print("KOMPILACJA TESTOW")
env.Library('../libs/tcp',
tcp_source,
LINKFLAGS=LINKFLAGS,
CXXFLAGS=cxxflags)
print("KOMPILACJA TESOW SERVERA")
env.Program(target = ['test_suite'],
        source = ['test_suite.cpp',
        '../game_engine/game_engine.cpp',
        '../game_engine/game_server.cpp',
        '../game_engine/game_client.cpp',
        '../game_objects/resources.cpp',
        '../game_objects/ship.cpp',
        '../game_objects/map_point.cpp',
        '../game_objects/game_object_factory.cpp',
        '../game_order/game_order.cpp',
        '../game_state/game_state.cpp'],
        LINKFLAGS=LINKFLAGS,
        LIBS=LIBS,
        LIBPATH=LIBPATH,
        CXXFLAGS = cxxflags);
