env = Environment()
LIBPATH = ['../libs/.']
cxxflags=['-std=c++17']
LIBS=['tcp','boost_regex']
LINKFLAGS=  ['-lpthread','-pthread']
tcp_source =[
        '../tcp/network/io_service.cpp',
        '../tcp/network/tcp_client.cpp',
        '../tcp/network/tcp_server.cpp',
        '../tcp/network/common/tcp_socket.cpp',
        '../tcp/network/unix/unix_self_pipe.cpp',
        '../tcp/network/unix/unix_tcp_socket.cpp',
        '../tcp/network/windows/windows_self_pipe.cpp',
        '../tcp/network/windows/windows_tcp_socket.cpp',
        '../tcp/utils/error.cpp',
        '../tcp/utils/logger.cpp',
        '../tcp/utils/thread_pool.cpp'
]
print("KOMPILACJA BIBLIOTEKI TCP")
env.Library('../libs/tcp',
tcp_source,
LINKFLAGS=LINKFLAGS,
CXXFLAGS=cxxflags)
print("KOMPILACJA TESOW SERVERA")
env.Program(target = ['game_server_test'],
        source = ['game_server_test.cpp',
        'game_engine.cpp',
        'game_server.cpp',
        '../game_state/game_state.cpp',
        '../game_objects/map_point.cpp',
        '../game_objects/player.cpp',
        '../game_objects/building.cpp',
        '../game_objects/ship.cpp',
        '../game_objects/resources.cpp'],
        LINKFLAGS=LINKFLAGS,
        LIBS=LIBS,
        LIBPATH=LIBPATH,
        CXXFLAGS = cxxflags);
print("KOMPILACJA TESOW KLIENTA1")
env.Program(target = ['player1'],
        source = ['player1.cpp','game_client.cpp'],
        LINKFLAGS= LINKFLAGS,
        LIBS=LIBS,
        LIBPATH=LIBPATH,
        CXXFLAGS = cxxflags);

print("KOMPILACJA TESOW KLIENTA2")
env.Program(target = ['player2'],
        source = ['player2.cpp','game_client.cpp'],
        LINKFLAGS= LINKFLAGS,
        LIBS=LIBS,
        LIBPATH=LIBPATH,
        CXXFLAGS = cxxflags);