env =Environment()
sources = ['tt.cpp']
lib_sources = ['game_engine.cpp', 'game_order.cpp', 'game_object_factory.cpp', 'game_state.cpp', 'ship.cpp']
cxxflags = ['-std=c++17', '-lboost_algorithm']
env.Library('game', lib_sources, CXXFLAGS = cxxflags)
env.Program(target='test', source = sources, LIBS = 'game', LIBPATH = '.', CXXFLAGS = cxxflags);

   
     
        
                  
      
  

